[cantfind]
isContextEnabled = true
content = """
# Couldn't find any videos for you!
This error means we couldn't find a video, we simply do not have it. 
Everything still shows up in search results, but that doesn't neccesarily mean we actually have a video of it.
"""

[addthis]
isContextEnabled = true
content = """
# Can you add X / When will Y be added?
Movie-web doesn't host its own content, and thus we do not know when something will be added, nor can we add something ourselves. 

Think of movie-web like google, we search the web for videos but we don't add our own, we only allow people to search.
"""

[legal]
isContextEnabled = true
content = """
# Where does our content come from? Is it legal?
We take the content directly from other sites that host content. We do not own any of the files. We simply display what we find on other sites.

Think of it like Google, we search the Internet for videos, but we dont own the sites, nor the content. We merely link to them.

Thus, the legality of watching the video depends on what sites it took from. We do not control that however. You can check the source section of the video settings to see what site you're watching from.
"""

[cantdownload]
isContextEnabled = true
content = """
# How to download?
Under the settings cog in the video player, you can find the download setting.

**If the option mentions downloading a playlist, then you'll be downloading a HLS playlist, you can play this file using VLC.**
Currently, the only source that supports downloading an MP4 file is Showbox, but this source is not available if you're using the public proxy.
"""

[episodes]
isContextEnabled = true
content = """
# How can I change episodes or seasons?
To switch which episode you're watching, you can click the [button](https://media.discordapp.net/attachments/871713465578979351/1135095318036353105/image.png) shown below in the video player. 
To change seasons, you can also click the same button but then select "Seasons" top right of the popup. 
"""

[dubs]
isContextEnabled = true
content = """
# Can I play this movie or TV show in another language?
It's not possible to watch content in other languages on movie-web. We don't intend to add this feature soon, so you're most likely better off searching for a website that provides content in your desired language!
Here is a list of non-English sites: <https://fmhy.pages.dev/non-english>
Find your language in the sidebar and look under the Streaming section. [Use this adblocker!](<https://ublockorigin.com>)
"""

[iphonecaptions]
isContextEnabled = true
content = """
# Why can't I see subtitles in fullscreen on my iPhone?
iOS does not allow custom video players to go fullscreen. Because of this, our subtitle renderer is not visible when you enter fullscreen.
We can't currently fix this, but we're hoping to fix it in version 4.
"""

[apps]
isContextEnabled = true
content = """
# Where is the app download?
While there are no native movie-web apps, you can install it as a [PWA](https://cdn.discordapp.com/attachments/656888828430385171/1174969037403459624/IMG_4763_1.PNG) on mobile devices:
[iOS guide](<https://www.wikihow.com/Install-Web-Apps-on-iPhone-or-iPad>)
[Android guide](<https://support.google.com/chrome/answer/9658361?co=GENIE.Platform%3DAndroid&oco=1>)
"""

[v5]
isContextEnabled = true
content = """
# When will v5 come out?
We don't know. We're working on it, but we don't have a release date yet:tm:.

You can check the planned features and their status [here](https://github.com/orgs/movie-web/projects/2).
If you're a developer and want to help, you can ask to be assigned to an issue on GitHub.
"""

[theatre]
isContextEnabled = true
content = """
# Why can't I watch this movie yet?

The movie you are trying to watch only came out in theatres very recently. We don't control our content, and it is not possible for us to show movies that haven't come out on streaming yet. 

We also won't point you to any other sources, so you're best off going to the actual movie theatre or waiting until it comes out on streaming. Asking for or providing other sources is against the rules and will result in a ban.
"""

[squeezebox]
isContextEnabled = true
content = """
# What is the new domain? Why did the site stop working?

The site has moved to https://movie-web.app. The old domain is no longer functional. It stopped working because we moved to a new domain. Update your bookmarks, tell your friends! Don't ask us restore functionality to the old link, or else ðŸ˜ˆ
"""

[showbox]
isContextEnabled = true
content = """
# What happened to Showbox/Febbox?

[Showbox/Febbox is no longer supported on our public proxies](<https://discord.com/channels/871713465100816424/1116430057922121760/1194388487424708788>), meaning that you have to host one yourself.
Doing so is simple and can be done for free and within 5 minutes, see [here](<https://docs.movie-web.app/proxy/deploy>).

If you need any extra help with setting up a custom proxy, you can ask for help in the [#custom-proxy](<https://discord.com/channels/871713465100816424/1194388816279113798>) channel.
"""

[hls]
isContextEnabled = true
content = """
# Why can't I download an MP4?

Most of our sources do not support downloading an MP4 file, this is because they use HLS (HTTP Live Streaming) to serve the video. HLS is a streaming protocol, and thus does not allow downloading the video itself.

However, you can download the HLS playlist by clicking the "Download playlist" button in the download menu.
Once downloaded, use VLC to play the m3u8 playlist file.
"""